### ISSUE TITLE
Cannot parse config file

### ISSUE THREAD

**Issue by ynzheng** [zlq4863947/triangular-arbitrage#1]
hello 

I tried this code,but it show me the following error 

any help?

thanks

me@vultr:~/projects/triangular-arbitrage$ npm start

> triangular-arbitrage@0.1.0 start /home/me/projects/triangular-arbitrage
> npm run prepare && node dist/index.js

> triangular-arbitrage@0.1.0 prepare /home/me/projects/triangular-arbitrage
> npm run rm && tsc -p tsconfig.json

> triangular-arbitrage@0.1.0 rm /home/me/projects/triangular-arbitrage
> rimraf dist

/home/me/projects/triangular-arbitrage/node_modules/config/lib/config.js:946
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: '/home/me/projects/triangular-arbitrage/config/default.toml': SyntaxError: Expected "'", "'''", "+", "-", "[", "\"", "\"\"\"", "_", "false", "true", "{", [ \t] or [0-9] but "l" found.
    at Config.util.parseFile (/home/me/projects/triangular-arbitrage/node_modules/config/lib/config.js:946:11)
    at /home/me/projects/triangular-arbitrage/node_modules/config/lib/config.js:715:28
    at Array.forEach (<anonymous>)
    at /home/me/projects/triangular-arbitrage/node_modules/config/lib/config.js:711:14
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (/home/me/projects/triangular-arbitrage/node_modules/config/lib/config.js:710:13)
    at new Config (/home/me/projects/triangular-arbitrage/node_modules/config/lib/config.js:135:27)
    at Object.<anonymous> (/home/me/projects/triangular-arbitrage/node_modules/config/lib/config.js:1780:31)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! triangular-arbitrage@0.1.0 start: `npm run prepare && node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the triangular-arbitrage@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2018-02-25T13_21_50_154Z-debug.log

**Comment by zlq4863947** [comment]
Toml suffix change to json, and then through [this address](https://toml-to-json.matiaskorhonen.fi/), the toml format configuration converted to json format.

**Comment by zlq4863947** [comment]
This bug has been fixed, please update to test
