### ISSUE TITLE
三角套利交易算法问题

### ISSUE THREAD

**Issue by zlq4863947** [zlq4863947/triangular-arbitrage#13]
### 套利标的信息：

```
{
    "id": "ETH-BTC-ADA",
    "a": {
        "coinFrom": "ETH",
        "coinTo": "BTC",
        "pair": "ETH/BTC",
        "side": "sell",
        "price": 0.076252,
        "quantity": 0.102,
        "conversionRate": 13.11441011383308
    },
    "b": {
        "coinFrom": "BTC",
        "coinTo": "ADA",
        "pair": "ADA/BTC",
        "side": "buy",
        "conversionRate": 0.00002348,
        "price": 0.00002348,
        "quantity": 591
    },
    "c": {
        "coinFrom": "ADA",
        "coinTo": "ETH",
        "pair": "ADA/ETH",
        "side": "sell",
        "price": 0.00030802,
        "quantity": 6147,
        "conversionRate": 3246.5424323095904
    },
    "rate": 0.03041329,
    "ts": 1520536682458
}
```

- 程序交易代码 ：
 https://github.com/zlq4863947/triangular-arbitrage/blob/develop/src/lib/trading.ts#L37-L96

- BigNumber语法说明
 `times`: 乘法
 `div`: 除法
 `plus`: 加法
 `minus`: 减法

----------

### 逻辑说明
现在已有上面的套利组合信息，套利对象为：`ETH`，

- A点:ETH/BTC
现有资产：`0.5 ETH`
 汇率为：`0.076252`，挂单量为：`0.102`
 程序判断`side= "sell"`,所以换算`BTC`为乘法
换成BTC:  `0.5 ETH` x  `0.076252` = `0.038126 BTC`

|最小交易数量  | 最小交易价格 | 最小下单总金额  | 
|--|--|--|
| 0.001 ETH | 0.000001 BTC| 0.001 BTC|

- B点:ADA/BTC
现有资产：`0.038126 BTC`
汇率为：`0.00002348`，挂单量为：`591`
 程序判断`side= "buy"`,所以换算`ADA`为除法
换成ADA:  `0.038126 BTC` /  `0.00002348` = `1693 ADA`

|最小交易数量  | 最小交易价格 | 最小下单总金额  | 
|--|--|--|
| 1 ADA | 0.00000001 BTC| 0.001 BTC|

- C点:ADA/ETH
现有资产：`1693 ADA`
汇率为：`0.00030802`，挂单量为：`6147`
 程序判断`side= "sell"`,所以换算`ETH`为乘法
换成ETH:  `1693 ADA` x `0.00030802` = `0.52147786 ETH`

|最小交易数量  | 最小交易价格 | 最小下单总金额  | 
|--|--|--|
| 1 ADA | 0.00000001 ETH| 0.01 ETH|

### 问题点
- B点的挂单量为`591`, 但是要卖的量有`1693`, 现在想到的解决办法是按`限价单`以`1693`卖出。
- [最小交易单位](https://support.binance.com/hc/zh-cn/articles/115000594711-%E5%90%84%E5%B8%82%E5%9C%BA%E4%BA%A4%E6%98%93%E8%A7%84%E5%88%99%E5%8F%82%E6%95%B0)计算加入到上面的公式上的结果？（这个可以参考交易代码）

**Comment by IMYin** [comment]
咱可以拆分来看，总共就3步， 第1步没问题，就是2和3之间会卡主，那么把2和3之间的挂单量进行比较，挑小的那个，然后换算成A币，这就是要进行套利的额度

**Comment by IMYin** [comment]
首先 A --->  B是没有问题的，都是大币种，量肯定没问题，就是B --> C ---> A 出问题，为了保证量的话，我们不妨将所有的币种的一天之中的交易量过滤下，找出排名靠前的一些币，只套利它们。
如果程序在测算期间是根据卖一价或者买一价来计算的，那么在卖不出去的时候或者买不进来的时候，就挂单行不行？直到交易完成，再进行下一步骤的交易，直到套利完成。


或者为了保证 B-->C顺利完成，我们在套利开始时，提前将B-->C的的挂单一价的 量提出来，保证B-->C能够顺利完成，那么就剩下C--->A了，

**Comment by IMYin** [comment]
威  13:16:16
两部分相等大于最小标准交易量+手续费，就进行套利
威  13:17:19
保险点，交易量小于一点相等量

**Comment by 1112LIN** [comment]
如果按照孙的 ，直接取B到C 这部分买一量 和 C到A这部分的卖1量进行比较。

**Comment by 1112LIN** [comment]
整理一下思路      A1-->B-->C-->A3
 第一步   B-->C   C的卖1量为D
               C-->A3   A3的卖1量为E           则交易量为X=D=E> min+0.1%  运行
                                                                                  X=D=E<min+0.1%  取消
 第二步       保险点 X=A1（）%-->换成使用A1的量

**Comment by IMYin** [comment]
举个栗子，**BTC** --->** ETH** ---> **ELF** 
第1步： 卖出**BTC**，换成**ETH**，看的是**BTC**对**ETH**的买一价
第2步： 用**ETH**买入**ELF**，看的是**ETH**对**ELF**的卖一价
第3步：卖出**ELF**，换成**BTC**，看的是**BTC**对**ELF**的买一价

所以，想要完成交易，第1步不用担心,；
分别对第2步中**ETH**对**ELF**的卖一价的量和**BTC**对**ELF**买一价的量，计算出价值多少**BTC**，选择值较小的；
如果这个值，满足（大于）平台设置的最小交易额度，则进行套利，否则套利取消。

伪代码：

```
初始交易金额 = 0

B2C_ask_volumn = get_volumn()
B2C_ask_price = get_price()
B2C_cost = B2C_ask_volumn * B2C_ask_price

C2A_bid_volumn = get_volumn()
C2A_bid_price = get_price()
C2A_cost = C2A_bid_volumn * C2A_bid_price

if B2C_cost > C2A_cost and C2A_cost > 最小交易额度：
    初始交易金额  = C2A_cost
    套利开始
if C2A_cost > B2C_cost and B2C_cost > 最小交易额度：
    初始交易金额  = B2C_cost
    套利开始
```

**Comment by zlq4863947** [comment]
```

初始交易金额 = 0
// B2C_cost = B2C_ask_volumn * B2C_ask_price
B2C总价 = 0.00002348 * 591 = 0.01387668 BTC

B2C总价_ETH = 0.01387668 BTC / 0.076252 = 0.1819844725384252

// C2A_cost = C2A_bid_volumn * C2A_bid_price
C2A总价 = 0.00030802 * 6147 = 1.89339894 ETH

然后取最小的
```

**Comment by zlq4863947** [comment]
### 套利标的信息2：

```
{
    "id": "BTC-ETH-SALT",
    "a": {
        "coinFrom": "BTC",
        "coinTo": "ETH",
        "pair": "ETH/BTC",
        "side": "buy",
        "conversionRate": 0.078563,
        "price": 0.078563,
        "quantity": 1.67
    },
    "b": {
        "coinFrom": "ETH",
        "coinTo": "SALT",
        "pair": "SALT/ETH",
        "side": "buy",
        "conversionRate": 0.004515,
        "price": 0.004515,
        "quantity": 0.01
    },
    "c": {
        "coinFrom": "SALT",
        "coinTo": "BTC",
        "pair": "SALT/BTC",
        "side": "sell",
        "price": 0.000355,
        "quantity": 100.75,
        "conversionRate": 2816.9014084507044
    },
    "rate": 0.08120815,
    "ts": 1520659933180
}
```

|最小交易数量  | 最小交易价格 | 最小下单总金额  | 
|--|--|--|
| 0.001 ETH | 0.000001 BTC| 0.001 BTC|
| 0.01 SALT | 0.000001 ETH| 0.01 ETH|
| 0.01 SALT | 0.000001 BTC| 0.001 BTC|

```

初始交易金额 = 0
// B2C_cost = B2C_volumn / B2C_price
B2C总价 = 0.01 ETH / 0.004515= 2.21 SALT
B2C总价_BTC = 2.21 SALT x 0.000355 = 0.000784 BTC

// C2A_cost = C2A_volumn * C2A_price
C2A总价 = 0.000355 * 100.75 = 0.03576625 BTC

```
