### ISSUE TITLE
运行项目报错: Argument of type 'string' is not assignable to parameter of type 'number'.

### ISSUE THREAD

**Issue by xiaoxin233** [zlq4863947/triangular-arbitrage#37]
src/lib/api-handler.ts:41:72 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.

41     return await api.createOrder(order.symbol, order.type, order.side, String(order.amount), String(order.price));

**Comment by zlq4863947** [comment]
嗯 你升级ccxt了吧？ 新版好像要传number类型的， 你改成number试试

**Comment by xiaoxin233** [comment]
嗯，是npm install时自动升级了依赖包。新版的ccxt需要传number类型
