### ISSUE TITLE
算法可以解释一下吗？

### ISSUE THREAD

**Issue by mrdongmen** [zlq4863947/triangular-arbitrage#43]
https://github.com/zlq4863947/triangular-arbitrage/blob/1e375fff10ec69e9972b6c098d4d834b0efd805a/src/lib/engine.ts

https://github.com/tiagosiebler/TriangularArbitrage/blob/master/lib/CurrencyCore.js

**Comment by zlq4863947** [comment]
嗯 最开始做的时候 有参照他那个代码，不过他那个算法有问题。
最后算出来利润是10%，三角套利不可能有那么高利润。

我这个把他那个算法已经改进好了，青出于蓝而胜于蓝：）
