### ISSUE TITLE
Paid version

### ISSUE THREAD

**Issue by ref-dat** [zlq4863947/triangular-arbitrage#47]
Hi bro,

I contacted you via Email regarding some paid version that works well and make some profits,

This is my email I case you didn't receive my message:
a.himite@gmail.com

Regards,

**Comment by ynzheng** [comment]
付费版是不再维护了么

**Comment by zlq4863947** [comment]
是的，目前免费版和付费版都以不在维护。

等以后有时间在做个新版本带图形界面的。
不过目前比较忙，暂时没时间。。。
